import { Button, CheckBox, ComboBox, TextEdit, Palette, ListView } from "std-widgets.slint";
import { Rt-Sa-List } from "rt-sa-list.slint"; 
import { Rt-Sa-Grid } from "rt-sa-grid.slint"; 
import { Rt-Sa-Globals } from "globals.slint";

export global guiGlobals {
    in property <string> device;
}

export component AppWindow inherits Window {
    title: "MIL-STD-1553 Bus Monitor";

    min-width: 800px;
    min-height: 400px;

    callback connectPressed();
    callback saSelected <=> Rt-Sa-Globals.saSelected;

    public function setError(errorMsg: string) {
        errorText.color = Colors.red;
        errorText.text = errorMsg;
    }

    public function setConnectStatus(status: bool) {
        if (status) {
            errorText.color = Colors.green;
            errorText.text = "Connected to device " + guiGlobals.device;
        } else {
            // Failure status message set by setError
        }
    }

    public function setFilterText(text: string) {
        filter-text.text = text;
    }

    public function setMessages(message: string) {
        messages-text-area.text += message;
        
        //Scroll down
        messages-text-area.viewport-y = min(0px, - messages-text-area.viewport-height + messages-text-area.visible-height);
    }

    init => {
        Palette.color-scheme = ColorScheme.dark;
    }

    VerticalLayout {
        padding-left: 15px;
        padding-right: 15px;
        spacing: 5px;

        HorizontalLayout {
            HorizontalLayout {
                padding: 15px;
                spacing: 10px;
                alignment: start;

                Text {
                    text: "Device#: ";
                    font-size: 15px;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }

                device-box := TextInput {
                    Rectangle {
                        background: gray;
                        opacity: 20%;
                        width: 100%;
                        height: 100%;
                    }

                    font-size: 20px;
                    height: 40px;
                    width: 65px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: "0000";
                }

                Button {
                    text: "Connect";
                    primary: true;
                    clicked => {
                        guiGlobals.device = device-box.text;
                        connectPressed();
                    }
                }
            }
        }

        // Rt-Sa-List {
        //     width: 150px;
        // }

        Rt-Sa-Grid {
            max-height: 440px;
        }

        HorizontalLayout {
            Text {
                text: "Messages";
                vertical-alignment: bottom;
                horizontal-alignment: left;
                padding-top: 10px;
                font-size: 20px;
                width: 110px;
            }

            filter-text := Text {
                text: "(No Filter)";
                vertical-alignment: TextVerticalAlignment.bottom;
                horizontal-alignment: TextHorizontalAlignment.left;
                padding-top: 10px;
                font-size: 15px;
            }
        }

        messages-text-area := TextEdit {
            padding-top: 10px;
            read-only: true;
        }

        HorizontalLayout {
            height: 20px;
            padding-left: 10px;
            padding-right: 10px;

            errorText := Text {
                text: "Ready, press connect";
                color: green;
            }

            Text {
                horizontal-alignment: right;
                text: "v1.0";
            }
        }
    }
}
